CREATE TABLE "T_ALLOC"
   (
    "ID" VARCHAR2(20),
	"BIZ_TAG" VARCHAR2(100),
	"MAX_ID" NUMBER,
	"STEP" NUMBER,
	"CREATE_TIME" TIMESTAMP ,
	"UPDATE_TIME" TIMESTAMP ,
	"VERSION" NUMBER,
	CONSTRAINT "T_ALLOC_PK" PRIMARY KEY ("ID")
   ) ;