#server:
#  servlet:
#    context-path: /fsip-demo
#  prot: 8080
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.101.201:8761/eureka/
spring:
  application:
    name: id-demo
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.96.7:1521/orcl
#    username: sofa_qqq
#    password: sofa_qqq
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sofa?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    default-auto-commit: true
    auto-commit: true
    maximum-pool-size: 100
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    minEvictableIdleTimeMillis: 300000
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #这个是时区，一定要加，否则会默认为格林尼治时间，即少8小时
    time-zone: GMT+8

logging:
  config: classpath:logback-spring.xml
id:
  server:
    url: http://127.0.0.1:8091
fsip:
  web:
    auditlog:
      request: false
