#server:
#  servlet:
#    context-path: /fsip-demo
#  prot: 8080
server:
  port: 8091

spring:
  application:
    name: service-portal
  datasource:
    #    driver-class-name: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@192.168.102.11:1521/ORCL
    #    username: fsip_test
    #    password: fsip_test
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sofa?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    default-auto-commit: true
    auto-commit: true
    maximum-pool-size: 100
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    minEvictableIdleTimeMillis: 300000
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #这个是时区，一定要加，否则会默认为格林尼治时间，即少8小时
    time-zone: GMT+8

logging:
  config: classpath:logback-spring.xml
id:
  segement:
    step: 10
  snowflake:
    step: 40
    workerId: 23